{% set name = "posthog" %}
{% set version = "3.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f6af935f1be5c5fb80351e71e0406af04bdc7da8e1b239ec630d7b60b0bdc4b7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7.0
    - pip
  run:
    - python >=3.7.0
    - requests >=2.7.0,<3.0.0
    - six >=1.5.0
    - monotonic >=1.5.0
    - backoff >=1.10.0
    - python-dateutil >=2.1.0

test:
  imports:
    - posthog
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PostHog/posthog-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Integrate PostHog into any python application

extra:
  recipe-maintainers:
    - Twixes
    - yakkomajuri
    - neilkakkar
    - posthog-bot
