{% set name = "posthog" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27dbf537241a69fb5f6a3e9561caa2d555d5891d95fa65c27ffa6b52d1fb63b6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7.0
    - pip
  run:
    - python >=3.7.0
    - requests >=2.7.0,<3.0.0
    - six >=1.5.0
    - monotonic >=1.5.0
    - backoff >=1.10.0
    - python-dateutil >=2.1.0

test:
  imports:
    - posthog
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PostHog/posthog-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Integrate PostHog into any python application

extra:
  recipe-maintainers:
    - Twixes
    - yakkomajuri
    - neilkakkar
    - posthog-bot
