{% set name = "posthog" %}
{% set version = "7.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55f7580265d290936ac4c112a4e2031a41743be4f90d4183ac9f85b721ff13ae

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.7.0,<3.0.0
    - six >=1.5.0
    - monotonic >=1.5.0
    - backoff >=1.10.0
    - python-dateutil >=2.2.0
    - distro >=1.5.0 # Required for Linux OS detection in Python 3.9+
    - typing-extensions >=4.2.0

test:
  imports:
    - posthog
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/PostHog/posthog-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Integrate PostHog into any python application

extra:
  recipe-maintainers:
    - Twixes
    - dmarticus
    - k11kirky
    - posthog-bot
