{% set name = "posthog" %}
{% set version = "4.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 513bfbb21344013294abc046b1142173189c5422a3906cf2280d1389b0c2e28b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.7.0,<3.0.0
    - six >=1.5.0
    - monotonic >=1.5.0
    - backoff >=1.10.0
    - python-dateutil >=2.1.0
    - distro >=1.5.0 # Required for Linux OS detection in Python 3.9+

test:
  imports:
    - posthog
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/PostHog/posthog-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Integrate PostHog into any python application

extra:
  recipe-maintainers:
    - Twixes
    - dmarticus
    - k11kirky
    - posthog-bot
