{% set name = "posthog" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: acb90b13bb757e8390f952374d40f8da28a432040f0c076334a264e161ec8aef

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7.0,<4.0.0
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - requests >=2.7.0,<3.0.0
    - six >=1.5.0,<2.0.0
    - monotonic >=1.5.0,<2.0.0
    - backoff >=1.10.0,<2.0.0
    - python-dateutil >=2.1.0,<3.0.0

test:
  imports:
    - posthog
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PostHog/posthog-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Integrate PostHog into any python application

extra:
  recipe-maintainers:
    - Twixes
    - yakkomajuri
    - neilkakkar
    - posthog-bot
